version: "3.8"
services:
 api:
  build: .
  ports:
   - "3000:3000"
  depends_on:
    - db
  links:
    - db
  volumes:
    - .:/app
  command: npm run dev

 db:
  platform: linux/x86_64
  image: mysql:5.7
  restart: always
  environment:
    MYSQL_DATABASE: 'db'
    # So you don't have to use root, but you can if you like
    MYSQL_USER: 'user'
    # You can use whatever password you like
    MYSQL_PASSWORD: 'password'
    # Password for root access
    MYSQL_ROOT_PASSWORD: 'password'
  ports:
    # <Port exposed> : < MySQL Port running inside container>
    - '3306:3306'
  expose:
    # Opens port 3306 on the container
    - '3306'
    # Where our data will be persisted
  volumes:
    - ./backup/mysql:/var/lib/mysql

 mongo-express:
  image: mongo-express
  restart: always
  ports:
    - 8081:8081
  environment:
    ME_CONFIG_MONGODB_ADMINUSERNAME: root
    ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

 adminer:
  image: adminer
  restart: always
  ports:
    - 8080:8080